/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceRange = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Category = IDL.Variant({
  'Cleaning' : IDL.Null,
  'Plumbing' : IDL.Null,
  'Painting' : IDL.Null,
  'Tailoring' : IDL.Null,
  'Tutoring' : IDL.Null,
  'Carpentry' : IDL.Null,
  'CarRepair' : IDL.Null,
  'ACRepair' : IDL.Null,
  'Others' : IDL.Null,
  'Electrical' : IDL.Null,
});
export const AddProviderArgs = IDL.Record({
  'area' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'priceRange' : PriceRange,
  'experience' : IDL.Nat,
  'availability' : IDL.Text,
  'address' : IDL.Text,
  'category' : Category,
  'phone' : IDL.Text,
});
export const ProviderId = IDL.Nat;
export const ProviderView = IDL.Record({
  'id' : ProviderId,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'priceRange' : PriceRange,
  'experience' : IDL.Nat,
  'availability' : IDL.Text,
  'address' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
});
export const PageResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(ProviderView),
});
export const UpdateProviderArgs = IDL.Record({
  'id' : ProviderId,
  'area' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'email' : IDL.Opt(IDL.Text),
  'priceRange' : IDL.Opt(PriceRange),
  'experience' : IDL.Opt(IDL.Nat),
  'availability' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addProvider' : IDL.Func([AddProviderArgs], [ProviderId], []),
  'getProvider' : IDL.Func([ProviderId], [IDL.Opt(ProviderView)], ['query']),
  'listProviders' : IDL.Func([IDL.Nat, IDL.Nat], [PageResult], ['query']),
  'listProvidersByArea' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'listProvidersByCategory' : IDL.Func(
      [Category, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'searchProviders' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'updateProvider' : IDL.Func([UpdateProviderArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceRange = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Category = IDL.Variant({
    'Cleaning' : IDL.Null,
    'Plumbing' : IDL.Null,
    'Painting' : IDL.Null,
    'Tailoring' : IDL.Null,
    'Tutoring' : IDL.Null,
    'Carpentry' : IDL.Null,
    'CarRepair' : IDL.Null,
    'ACRepair' : IDL.Null,
    'Others' : IDL.Null,
    'Electrical' : IDL.Null,
  });
  const AddProviderArgs = IDL.Record({
    'area' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'priceRange' : PriceRange,
    'experience' : IDL.Nat,
    'availability' : IDL.Text,
    'address' : IDL.Text,
    'category' : Category,
    'phone' : IDL.Text,
  });
  const ProviderId = IDL.Nat;
  const ProviderView = IDL.Record({
    'id' : ProviderId,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'priceRange' : PriceRange,
    'experience' : IDL.Nat,
    'availability' : IDL.Text,
    'address' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
  });
  const PageResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(ProviderView),
  });
  const UpdateProviderArgs = IDL.Record({
    'id' : ProviderId,
    'area' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'email' : IDL.Opt(IDL.Text),
    'priceRange' : IDL.Opt(PriceRange),
    'experience' : IDL.Opt(IDL.Nat),
    'availability' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addProvider' : IDL.Func([AddProviderArgs], [ProviderId], []),
    'getProvider' : IDL.Func([ProviderId], [IDL.Opt(ProviderView)], ['query']),
    'listProviders' : IDL.Func([IDL.Nat, IDL.Nat], [PageResult], ['query']),
    'listProvidersByArea' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'listProvidersByCategory' : IDL.Func(
        [Category, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'searchProviders' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'updateProvider' : IDL.Func([UpdateProviderArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };