/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProviderView {
    id: ProviderId;
    area: string;
    name: string;
    description: string;
    isActive: boolean;
    email: string;
    priceRange: PriceRange;
    experience: bigint;
    availability: string;
    address: string;
    category: Category;
    rating: number;
    phone: string;
    reviewCount: bigint;
}
export type ProviderId = bigint;
export interface AddProviderArgs {
    area: string;
    name: string;
    description: string;
    email: string;
    priceRange: PriceRange;
    experience: bigint;
    availability: string;
    address: string;
    category: Category;
    phone: string;
}
export interface UpdateProviderArgs {
    id: ProviderId;
    area?: string;
    name?: string;
    description?: string;
    isActive?: boolean;
    email?: string;
    priceRange?: PriceRange;
    experience?: bigint;
    availability?: string;
    address?: string;
    category?: Category;
    phone?: string;
}
export interface PageResult {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<ProviderView>;
}
export enum Category {
    Cleaning = "Cleaning",
    Plumbing = "Plumbing",
    Painting = "Painting",
    Tailoring = "Tailoring",
    Tutoring = "Tutoring",
    Carpentry = "Carpentry",
    CarRepair = "CarRepair",
    ACRepair = "ACRepair",
    Others = "Others",
    Electrical = "Electrical"
}
export enum PriceRange {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export interface backendInterface {
    addProvider(args: AddProviderArgs): Promise<ProviderId>;
    getProvider(id: ProviderId): Promise<ProviderView | null>;
    listProviders(page: bigint, pageSize: bigint): Promise<PageResult>;
    listProvidersByArea(area: string, page: bigint, pageSize: bigint): Promise<PageResult>;
    listProvidersByCategory(category: Category, page: bigint, pageSize: bigint): Promise<PageResult>;
    searchProviders(keyword: string, page: bigint, pageSize: bigint): Promise<PageResult>;
    updateProvider(args: UpdateProviderArgs): Promise<boolean>;
}
import type { AddProviderArgs as _AddProviderArgs, Category as _Category, PageResult as _PageResult, PriceRange as _PriceRange, ProviderId as _ProviderId, ProviderView as _ProviderView, UpdateProviderArgs as _UpdateProviderArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProvider(arg0: AddProviderArgs): Promise<ProviderId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProvider(to_candid_AddProviderArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProvider(to_candid_AddProviderArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getProvider(arg0: ProviderId): Promise<ProviderView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProviders(arg0: bigint, arg1: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listProviders(arg0, arg1);
                return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProviders(arg0, arg1);
            return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProvidersByArea(arg0: string, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listProvidersByArea(arg0, arg1, arg2);
                return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProvidersByArea(arg0, arg1, arg2);
            return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProvidersByCategory(arg0: Category, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listProvidersByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProvidersByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProviders(arg0: string, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProviders(arg0, arg1, arg2);
                return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProviders(arg0, arg1, arg2);
            return from_candid_PageResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProvider(arg0: UpdateProviderArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProvider(to_candid_UpdateProviderArgs_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProvider(to_candid_UpdateProviderArgs_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PageResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageResult): PageResult {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PriceRange_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceRange): PriceRange {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderView_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderView): ProviderView {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProviderView]): ProviderView | null {
    return value.length === 0 ? null : from_candid_ProviderView_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_ProviderView>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<ProviderView>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n16(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProviderId;
    area: string;
    name: string;
    description: string;
    isActive: boolean;
    email: string;
    priceRange: _PriceRange;
    experience: bigint;
    availability: string;
    address: string;
    category: _Category;
    rating: number;
    phone: string;
    reviewCount: bigint;
}): {
    id: ProviderId;
    area: string;
    name: string;
    description: string;
    isActive: boolean;
    email: string;
    priceRange: PriceRange;
    experience: bigint;
    availability: string;
    address: string;
    category: Category;
    rating: number;
    phone: string;
    reviewCount: bigint;
} {
    return {
        id: value.id,
        area: value.area,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        email: value.email,
        priceRange: from_candid_PriceRange_n10(_uploadFile, _downloadFile, value.priceRange),
        experience: value.experience,
        availability: value.availability,
        address: value.address,
        category: from_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        phone: value.phone,
        reviewCount: value.reviewCount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): PriceRange {
    return "Low" in value ? PriceRange.Low : "High" in value ? PriceRange.High : "Medium" in value ? PriceRange.Medium : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Cleaning: null;
} | {
    Plumbing: null;
} | {
    Painting: null;
} | {
    Tailoring: null;
} | {
    Tutoring: null;
} | {
    Carpentry: null;
} | {
    CarRepair: null;
} | {
    ACRepair: null;
} | {
    Others: null;
} | {
    Electrical: null;
}): Category {
    return "Cleaning" in value ? Category.Cleaning : "Plumbing" in value ? Category.Plumbing : "Painting" in value ? Category.Painting : "Tailoring" in value ? Category.Tailoring : "Tutoring" in value ? Category.Tutoring : "Carpentry" in value ? Category.Carpentry : "CarRepair" in value ? Category.CarRepair : "ACRepair" in value ? Category.ACRepair : "Others" in value ? Category.Others : "Electrical" in value ? Category.Electrical : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderView>): Array<ProviderView> {
    return value.map((x)=>from_candid_ProviderView_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AddProviderArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddProviderArgs): _AddProviderArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PriceRange_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): _PriceRange {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProviderArgs_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProviderArgs): _UpdateProviderArgs {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProviderId;
    area?: string;
    name?: string;
    description?: string;
    isActive?: boolean;
    email?: string;
    priceRange?: PriceRange;
    experience?: bigint;
    availability?: string;
    address?: string;
    category?: Category;
    phone?: string;
}): {
    id: _ProviderId;
    area: [] | [string];
    name: [] | [string];
    description: [] | [string];
    isActive: [] | [boolean];
    email: [] | [string];
    priceRange: [] | [_PriceRange];
    experience: [] | [bigint];
    availability: [] | [string];
    address: [] | [string];
    category: [] | [_Category];
    phone: [] | [string];
} {
    return {
        id: value.id,
        area: value.area ? candid_some(value.area) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        priceRange: value.priceRange ? candid_some(to_candid_PriceRange_n3(_uploadFile, _downloadFile, value.priceRange)) : candid_none(),
        experience: value.experience ? candid_some(value.experience) : candid_none(),
        availability: value.availability ? candid_some(value.availability) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n5(_uploadFile, _downloadFile, value.category)) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    area: string;
    name: string;
    description: string;
    email: string;
    priceRange: PriceRange;
    experience: bigint;
    availability: string;
    address: string;
    category: Category;
    phone: string;
}): {
    area: string;
    name: string;
    description: string;
    email: string;
    priceRange: _PriceRange;
    experience: bigint;
    availability: string;
    address: string;
    category: _Category;
    phone: string;
} {
    return {
        area: value.area,
        name: value.name,
        description: value.description,
        email: value.email,
        priceRange: to_candid_PriceRange_n3(_uploadFile, _downloadFile, value.priceRange),
        experience: value.experience,
        availability: value.availability,
        address: value.address,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        phone: value.phone
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == PriceRange.Low ? {
        Low: null
    } : value == PriceRange.High ? {
        High: null
    } : value == PriceRange.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Cleaning: null;
} | {
    Plumbing: null;
} | {
    Painting: null;
} | {
    Tailoring: null;
} | {
    Tutoring: null;
} | {
    Carpentry: null;
} | {
    CarRepair: null;
} | {
    ACRepair: null;
} | {
    Others: null;
} | {
    Electrical: null;
} {
    return value == Category.Cleaning ? {
        Cleaning: null
    } : value == Category.Plumbing ? {
        Plumbing: null
    } : value == Category.Painting ? {
        Painting: null
    } : value == Category.Tailoring ? {
        Tailoring: null
    } : value == Category.Tutoring ? {
        Tutoring: null
    } : value == Category.Carpentry ? {
        Carpentry: null
    } : value == Category.CarRepair ? {
        CarRepair: null
    } : value == Category.ACRepair ? {
        ACRepair: null
    } : value == Category.Others ? {
        Others: null
    } : value == Category.Electrical ? {
        Electrical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
